version: '3.8'

services:
  # Development environment with hot reload
  dev:
    build:
      context: .
      target: dev
    container_name: ai-data-eng-dev
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      # Exclude node_modules to use container's version
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0

  # Production build
  prod:
    build:
      context: .
      target: production
    container_name: ai-data-eng-prod
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
